name: flutter_front
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  icons_plus: ^5.0.0
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.4
  country_code_picker: ^3.0.0
  modal_bottom_sheet: ^3.0.0
  intl_phone_field: ^3.1.0
  csc_picker: ^0.2.7
  http: ^1.2.1
  get: ^4.6.5
  shared_preferences: ^2.0.15
  dropdown_button2: ^2.3.9
  syncfusion_flutter_datepicker: ^25.1.37
  curved_navigation_bar: ^1.0.3
  jwt_decoder: ^2.0.1
  image_picker: ^1.1.1
  geolocator: ^11.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  google_maps_flutter: ^2.2.8
  mapbox_gl: ^0.16.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg1.png